# Generated by Django 5.1.2 on 2024-11-15 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_city_address_citys'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='citys',
            new_name='city',
        ),
    ]
