# Generated by Django 5.1.2 on 2024-11-20 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_deliveryboylocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboystatus',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryboystatus',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='DeliveryBoyLocation',
        ),
    ]
